### ISSUE TITLE
Exception When Publishing Edited Form

### ISSUE THREAD

**Issue by fldcf-kkaufmann** [Epi-Info/Epi-Info-Community-Edition#1]
When attempting to publish a form that has been edited (in the designer), the attached exception is generated.

Steps:
1. Create a new project
1. Create a single form
  a. Add a text input to form
1. Publish form
1. Add an additional text input to form
1. Publish form from Quick Publish toolbar menu item

*this.mediator.ProjectExplorer.CurrentView* is null. The issue does seem to be intermittent, however, and cannot be reproduced consistently.

![image](https://user-images.githubusercontent.com/42809443/44794202-fa14f180-ab75-11e8-9073-8682ac7755ed.png)

**Comment by cdc-dpbrown** [comment]
Hello kkaufmann,

The code is getting the CurrentView.Id from the ProjectExplorer (tree control) when it should just be pulling it from the currently instantiated view. You see the problem when a tree node is selected that is not a view so you only see it some of the time. We will fix and test the bug but if you just want to get over this bump you could replace _**this.mediator.ProjectExplorer.CurrentView.Id**_ with _**this.CurrentView.id**_.
Thanks for writing this issue up and bringing it to our attention.

Thank you,
David

**Comment by fldcf-kkaufmann** [comment]
David,

I am able to reproduce the behavior as described. I concur with your assessment.

Our agency hasn't been building from source, and we'be been using the installer to load the software. Do you update the installer at regular intervals, or do you update it as you find issues?

Thanks,

Kenneth K.

**Comment by cdc-dpbrown** [comment]
Hello Kenneth,

I guess you could say, somewhat regular intervals. We were just finishing up testing but I'll roll this one into the next build which should come out pretty soon.

Thank you,
David
