### ISSUE TITLE
Can add external data from excel after finishing creating form?

### ISSUE THREAD

**Issue by xh542428798** [Epi-Info/Epi-Info-Community-Edition#10]
I am creating a data entry form, and I would like to ask if, after I have finished the form and entered some data, my colleague has entered another batch of data using Excel, can I append my colleague’s Excel data to the part that I have entered?

**Comment by cdc-dpbrown** [comment]
Hi Hui, 

Yes, but I believe you mean to say Access not Excel. Epi Info 7 can read and analyze data for Excel and other sources, but it can only collect data through its Enter Data module into MS SQL Server and Microsoft Access. To get instructions for merging your data, please ask our help desk (https://www.cdc.gov/epiinfo/support/helpdesk.html), we have two dedicated helpdesk personnel that can help you run your project. This form is more for reporting defects and requesting new features with the developers.

Thank you,
David
