### ISSUE TITLE
Which kind of encryption does Epi Info provides?

### ISSUE THREAD

**Issue by pablox-cl** [Epi-Info/Epi-Info-Community-Edition#2]
It just says about "save with a password" to encrypt", but if the data is going to to AWS or Box, I would like to know how is secured :) 

I don't know c#, but I looked into the code and I couldn't deduce it :cry: 

(My guess is somewhere here: https://github.com/Epi-Info/Epi-Info-Community-Edition/blob/139e004bf9b0252d650ebbc808da69999df0f55c/Epi.Core/Configuration_Static.cs#L1116)

**Comment by cdc-jtmiller** [comment]
@pablox-cl  Epi Info uses AES 128 bit encryption.
