### ISSUE TITLE
pls add batch import option in import from mobile device (image uploaded pls check it )

### ISSUE THREAD

**Issue by ghost** [Epi-Info/Epi-Info-Community-Edition#3]
pls add batch import option in import from mobile device (image uploaded pls check it )
![Screenshot_2 - Copy](https://user-images.githubusercontent.com/49126487/55293164-0c5b5480-5411-11e9-9574-cd8ec0c0a714.png)

**Comment by cdc-jtmiller** [comment]
A batch option has been added to version 7.2.6.0.

[](https://github.com/Epi-Info/Epi-Info-Community-Edition/releases/tag/7.2.6.0)
